[Infra] debug pip for serval

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -12,33 +12,33 @@ on:
         type: string
 
 jobs:
-  get-version:
-    runs-on: lynx-ubuntu-22.04-medium
-    timeout-minutes: 60
-    outputs:
-      version: ${{ steps.get_version.outputs.VERSION }}
-    steps:
-      - name: Get Version
-        id: get_version
-        run: |-
-          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
-            version=${{ github.event.inputs.tag }}
-          else
-            version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
-          fi
-          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ || \
-                $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ || \
-                $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+$ ]]; then
-            echo "Version is valid"
-            echo "VERSION=$version" >> $GITHUB_OUTPUT;
-          else
-            echo "Version is invalid"
-            exit 1
-          fi
+  # get-version:
+  #   runs-on: lynx-ubuntu-22.04-medium
+  #   timeout-minutes: 60
+  #   outputs:
+  #     version: ${{ steps.get_version.outputs.VERSION }}
+  #   steps:
+  #     - name: Get Version
+  #       id: get_version
+  #       run: |-
+  #         if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
+  #           version=${{ github.event.inputs.tag }}
+  #         else
+  #           version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
+  #         fi
+  #         if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ || \
+  #               $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ || \
+  #               $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+$ ]]; then
+  #           echo "Version is valid"
+  #           echo "VERSION=$version" >> $GITHUB_OUTPUT;
+  #         else
+  #           echo "Version is invalid"
+  #           exit 1
+  #         fi
 
   build-android:
     name: Build Android
-    needs: get-version
+    # needs: get-version
     runs-on: lynx-ubuntu-22.04-large
     steps:
       - uses: actions/checkout@v3
@@ -47,33 +47,33 @@ jobs:
         with:
           java-version: 11
           distribution: "zulu"
-      - name: Setup Android SDK
-        uses: android-actions/setup-android@v3
-        with:
-          cmdline-tools-version: 9862592
+      # - name: Setup Android SDK
+      #   uses: android-actions/setup-android@v3
+      #   with:
+      #     cmdline-tools-version: 9862592
 
-      - name: Install CMake
-        run: echo "y" | sdkmanager --install "cmake;3.18.1"
+      # - name: Install CMake
+      #   run: echo "y" | sdkmanager --install "cmake;3.18.1"
 
-      - name: Build AAR
-        working-directory: svg/platform/android
-        run: |
-          chmod +x gradlew
-          ./gradlew assembleRelease
-          ./gradlew publish \
-          -Pversion=${{ needs.get-version.outputs.version }} \
-          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} \
-          -Psigning.password=${{ secrets.SIGNING_PASSWORD }} \
-          -Psigning.secretKey=${{ secrets.SIGNING_SECRET_KEY }}
-          ./gradlew zipArtifacts -Pversion=${{ needs.get-version.outputs.version }} getArtifactList
-          pushd build/
-          artifact_list=$(<artifact-list)
-          echo "artifact_list=$artifact_list" >> $GITHUB_OUTPUT;
-          popd
-        id: build_artifact
+      # - name: Build AAR
+      #   working-directory: svg/platform/android
+      #   run: |
+      #     chmod +x gradlew
+      #     ./gradlew assembleRelease
+      #     ./gradlew publish \
+      #     -Pversion=${{ needs.get-version.outputs.version }} \
+      #     -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} \
+      #     -Psigning.password=${{ secrets.SIGNING_PASSWORD }} \
+      #     -Psigning.secretKey=${{ secrets.SIGNING_SECRET_KEY }}
+      #     ./gradlew zipArtifacts -Pversion=${{ needs.get-version.outputs.version }} getArtifactList
+      #     pushd build/
+      #     artifact_list=$(<artifact-list)
+      #     echo "artifact_list=$artifact_list" >> $GITHUB_OUTPUT;
+      #     popd
+      #   id: build_artifact
 
       - name: Publish artifact to maven
-        uses: lynx-infra/maven-publish-action@2a55bab5273ffd84ebbb600e783286fc6251c239
+        uses: lynx-infra/maven-publish-action@fd093567a4d9f49f33170c9694a4ffede314a8d9
         with:
           portal_api_token: ${{ secrets.PORTAL_API_TOKEN }}
-          artifact_path_list: ${{ steps.build_artifact.outputs.artifact_list }}
+          artifact_path_list: 11111111
